### ISSUE TITLE
Add @mswami bio

### ISSUE THREAD

**Issue by madhuswami** [githubteacher/developers-aug-25-2015#8]
Madhu s
.Net Developer
Fremont, CA

**Comment by Rajm4** [comment]
hi Madhuswami,

Greetings of the day.

I have an opening for .Net developer with Mvc and Wcf for one of renowed client in Fremont-CA,I f at all you are looking fro any new projects do let me know or if you have any one you would like to recommend then please drop me an email on raj.mehta@prohubway.com.

Kind Regards
Raj
